name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.1
      with:
        node-version: 12.x
      
    # Instalar as dependências NPM/Yarn
    - name: Install dependencies
      run: yarn
    
    # Executar a Build
    - name: Run build
      run: yarn build

    # Copiar pasta dist pra dentro da Digital Ocean
    - name: Copy dist to Digital Ocean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: "dist"
        target: "test"
      
    # Substituir o código "dist" na pasta pelo atualizado
    # Executar "yarn" na Digital Ocean
    # Executar as migrations do TypeORM
    # Restart no servidor Node.js
